# Generated by Django 4.1.4 on 2022-12-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('veiculo', models.CharField(max_length=20)),
                ('km_Troca_Oleo', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='motorista',
            fields=[
                ('id_motorista', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=25)),
                ('Telefone', models.CharField(max_length=25)),
                ('CNH', models.CharField(max_length=25)),
            ],
        ),
    ]
